markdown: rdiscount
permalink: /:title/
url: http://tech.printf.me
name: tech.printf.me
author: zhiyue
qq: 245392756
email: cszhiyue@gmail.com
duoshuo: zhiyue
beian: 
cnzz: 
weibo: 2372807992
github: zhiyue
pygments: false
safe: true
paginate: 20
about: "这里是 zhiyue 的个人博客"
